ALTER TABLE public.youtube_channels
ADD COLUMN IF NOT EXISTS total_views BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS subscriber_count BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_count BIGINT DEFAULT 0;
